# Use an official Python runtime as a parent image
FROM python:3.11.5

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV FLASK_APP=main.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV SECRET_KEY=8BYkEfBA6O6donzWlSihBXox7C0sKR6b
ENV MOVIE_DB_API_KEY=your_movie_db_api_key
ENV DATABASE_URI=sqlite:///top_movies.db

# Run app.py when the container launches
CMD ["flask", "run", "--host=0.0.0.0", "--port=80"]

